"""create initial tables

Revision ID: c236a83a3171
Revises: 
Create Date: 2026-09-28 11:59:38.726560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c236a83a3171'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id_job', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=10), nullable=True),
    sa.Column('job_duration', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_job')
    )
    op.create_table('milestone',
    sa.Column('id_milestone', sa.Integer(), nullable=False),
    sa.Column('acheived', sa.Boolean(), nullable=True),
    sa.Column('date_acheived', sa.Date(), nullable=True),
    sa.Column('date_estimated', sa.Date(), nullable=True),
    sa.Column('milestone_distance', sa.Float(), nullable=True),
    sa.Column('milestone_speed', sa.Float(), nullable=True),
    sa.Column('milestone_type', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id_milestone')
    )
    op.create_table('running_history',
    sa.Column('id_run', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=True),
    sa.Column('run_distance', sa.Float(), nullable=True),
    sa.Column('run_time', sa.Float(), nullable=True),
    sa.Column('run_speed', sa.Float(), nullable=True),
    sa.Column('elevation', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_run')
    )
    op.create_table('training_day',
    sa.Column('id_training_day', sa.Integer(), nullable=False),
    sa.Column('training_day_date', sa.Date(), nullable=True),
    sa.Column('nb_trainings', sa.Integer(), nullable=True),
    sa.Column('training_day_completed', sa.Boolean(), nullable=True),
    sa.Column('training_day_duration', sa.Integer(), nullable=True),
    sa.Column('content_running', sa.String(), nullable=True),
    sa.Column('content_strength', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_training_day')
    )
    op.create_table('training',
    sa.Column('id_training', sa.Integer(), nullable=False),
    sa.Column('id_training_day', sa.Integer(), nullable=True),
    sa.Column('training_type', sa.String(length=10), nullable=True),
    sa.Column('training_duration', sa.Integer(), nullable=True),
    sa.Column('training_completed', sa.Boolean(), nullable=True),
    sa.Column('feedback', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['id_training_day'], ['training_day.id_training_day'], ),
    sa.PrimaryKeyConstraint('id_training')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training')
    op.drop_table('training_day')
    op.drop_table('running_history')
    op.drop_table('milestone')
    op.drop_table('job')
    # ### end Alembic commands ###
